authentic/urls.py
from django.urls import path
from . import views

app_name = 'authentic'

urlpatterns = [
    path('login/' , views.registerUser.as_view(), name='registerUser'),
    path('logout/', views.logoutUser, name='logoutUser')

]

comm/urls.py
from django.urls import path
from . import views 

app_name = 'comm'

urlpatterns = [
	path('<str:community_name>', views.communityDisplay, name = "communityDisplay"),
	path('<str:community_name>/search/', views.searchComm, name = "searchComm"),
	path('<str:community_name>/join/', views.API_join, name = "API_join"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from project_G3 import views as project_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project_G3.urls')),
    path('auth/', include('authentic.urls')),
    path('r/', include('comm.urls')),
    path("search/", include('search.urls')),
    path('u/', include('userpage.urls'))
]

project_G3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from comm import views as community_views

urlpatterns = [
	path('', views.index, name='index'),
	path('us', views.aboutUs, name='aboutUs'),
	path('postCreate', views.postCreate, name='postCreate'),
	path('<int:post_id>/', views.detail, name='detail'),
	path("communityCreate", community_views.communityCreate, name = 'communityCreate'),
	path('api/post/<int:post_id>/like', views.api_like),
    path('api/post/<int:post_id>/dislike', views.api_dislike),
	path('<int:post_id>/delete', views.delete, name='delete'),
	path('comments/<int:comment_id>/delete', views.delete_comment, name='delete_comment'),
	path('comments/<int:comment_id>/reply', views.reply_comment, name='reply_comment'),
	path('comments/reply/<int:reply_id>/delete', views.delete_reply, name='delete_reply'),
	path('<int:post_id>/edit', views.editPost, name='editPost'),
	path('editprofile', views.editProfile, name='editProfile'),
	path('<int:post_id>/savePost', views.savePost, name='savePost'),
	path('mainpage', views.mainpage, name = 'mainpage'),
	path('api/post/<int:post_id>/save', views.APIsave, name= 'APIsave'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views 

app_name = 'search'

urlpatterns = [
    path('', views.searchContent, name = "searchContent")
]

userpage/urls.py
from django.urls import path
from . import views 

app_name = 'userpage'

urlpatterns = [
    path('<str:user_name>/', views.userpage, name='userpage'),
    path('<str:username>/follow/', views.API_follow, name = "API_follow"),
]

project_G3/forms.py
from django import forms
from django.core.files.images import get_image_dimensions

from my_app.models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        try:
            w, h = get_image_dimensions(avatar)

            #validate dimensions
            max_width = max_height = 100
            if w > max_width or h > max_height:
                raise forms.ValidationError(
                    u'Please use an image that is '
                     '%s x %s pixels or smaller.' % (max_width, max_height))

            #validate content type
            main, sub = avatar.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError(u'Please use a JPEG, '
                    'GIF or PNG image.')

            #validate file size
            if len(avatar) > (20 * 1024):
                raise forms.ValidationError(
                    u'Avatar file size may not exceed 20k.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass

        return avatar

project_G3/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.utils import timezone
from django.views.generic import TemplateView, ListView, CreateView
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Count
from project_G3.models import Post, Comment, Community, UserProfile, Reply
import random

app_name = 'project_G3'


def getRandomAds():
    imgList = ["https://i.pinimg.com/originals/53/c6/d5/53c6d53c0a420d130ea23d645533c934.gif",
               "https://i.pinimg.com/originals/b0/1d/df/b01ddf257d18c8a9b41e0502161d580c.gif",
               "https://miro.medium.com/max/1400/1*VuRMGPKL5vgl_22OhhnbiQ.gif",
               "https://miro.medium.com/max/1400/1*Jy91LipOh3Pfl9GZugQLBw.gif",
               "https://media.giphy.com/media/3o6ZsVllI9P8PpM0Ao/giphy.gif",
               ]
    return imgList[random.randint(0, len(imgList) - 1)]


def getUserCommunity(request):
    try:
        communities = Community.objects.filter(members=request.user)
    except:
        communities = Community.objects.none()
    return communities
# Create your views here.


def sort(request, posts):
    if 'sort' in request.GET:
        if request.GET['sort'] == 'date':
            posts = posts.order_by('posted_at')
        elif request.GET['sort'] == 'like':
            posts = posts.annotate(like_count=Count(
                'liked')).order_by('-like_count')
        elif request.GET['sort'] == 'dislike':
            posts = posts.annotate(dislike_count=Count(
                'disliked')).order_by('-dislike_count')
        return posts
    else:
        return posts.order_by('-posted_at')


def index(request):


    communities = getUserCommunity(request)
    try:
        posts = Post.objects.filter(community__in=communities) | Post.objects.filter(
            author=request.user) | Post.objects.filter(author__in=request.user.userprofile.followed_users.all())
    except:
        posts = Post.objects.none()
    suggestedPost = []
    for post in Post.objects.all().annotate(like_count=Count('liked')).order_by('-like_count'):
        if (post not in posts):
            suggestedPost += [post]
    # print(suggestedPost)
    posts = sort(request, posts)
    if request.user.is_authenticated:
        player, created = UserProfile.objects.get_or_create(user=request.user)
    topCommunities = Community.objects.annotate(
        rank=Count('members')).order_by('-rank')[:5]
    newCommunities = Community.objects.all().order_by('-created_at')[:5]
    data = {
        'communities': communities,
        'posts': posts,
        'topCommunities': topCommunities,
        'newCommunities': newCommunities,
        'action': 'Home',
        'actionURL': "https://i.imgur.com/zmZkm8I.png",
        'ads': getRandomAds(),
        'suggestedPosts': suggestedPost[:5],
        'description': "Your personal FReddit frontpage. Come here to check in with your favorite communities.",
    }
    if request.user.is_authenticated:
        data['user'] = request.user
    else:
        data['user'] = None
    return render(request, 'project_G3/index.html', data)


def mainpage(request):
    communities = getUserCommunity(request)
    posts = sort(request, Post.objects)
    if request.user.is_authenticated:
        player, created = UserProfile.objects.get_or_create(user=request.user)
    topCommunities = Community.objects.annotate(
        rank=Count('members')).order_by('-rank')[:5]
    newCommunities = Community.objects.all().order_by('-created_at')[:5]
    data = {
        'communities': communities,
        'posts': posts,
        'topCommunities': topCommunities,
        'newCommunities': newCommunities,
        'action': 'Mainpage',
        'actionURL': "https://i.imgur.com/uOQZrhr.png",
        'description': "The most active posts from all of FReddit. Come here to see new posts rising and be a part of the conversation.",
        'ads': getRandomAds()
    }
    if request.user.is_authenticated:
        data['user'] = request.user
    else:
        data['user'] = None

    return render(request, 'project_G3/index.html', data)


def login(request):
    return render(request, 'auth/login.html')


@login_required(login_url='/auth/login/')
def postCreate(request):
    communities = getUserCommunity(request)
    community = ""
    content = {
        'communities': communities,
        'action': "Create post",
        'actionURL': "https://i.imgur.com/k3VFgYR.png",
    }
    if 'community' in request.GET:
        community = Community.objects.get(name=request.GET['community'])
        content["community"] = community
    if request.method == 'POST':
        # print(community.name)
        post = Post(title=request.POST['title'],
                    body=request.POST['text'],
                    posted_at=timezone.now(),
                    author=request.user,
                    )
        try:
            post.community = community
        except:
            print("There is no community")
        if not post.title:
            messages.info(request, 'Title is required')
            return render(request, 'project_G3/postCreate.html', content)
        try:
            
            print(str(request.FILES['media'])[-3:])
            if str(request.FILES['media'])[-3:]=='mp4' or str(request.FILES['media'])[-3:]=='m4v':
                post.video = request.FILES['media']
            elif str(request.FILES['media'])[-3:]=='mp3':
                post.audio = request.FILES['media']
            else:
                post.image = request.FILES['media']
        except:
            print("No media files")
        post.save()
        request.user.userprofile.createdposts.add(post)
        return redirect(detail, post_id=post.id)
    return render(request, 'project_G3/postCreate.html', content)


def detail(request, post_id):
    communities = getUserCommunity(request)
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404("Post does not exist")

    try:
        if post in request.user.userprofile.saved_posts.all():
            if request.method == "POST":
                if request.user.is_authenticated:
                    comment = Comment(
                        article=post, text=request.POST['text'], posted_by=request.user)
                    comment.save()
                    return redirect('/'+str(post_id)+"#cm")
                else:
                    messages.info(
                        request, 'You must be logged in to post a comment')
                    return render(request, "project_G3/detail.html", context)
            context = {
                "saved": "saved",
                "post": post,
                "comments": post.comments.all(),
                "comments_count": post.comments.all().count(),
                "viewing_user": request.user.username,
                'communities': communities,
                "action": "Post",
                "actionURL": "https://i.imgur.com/k3VFgYR.png",
                "ads" : getRandomAds()
            }
            return render(request, "project_G3/detail.html", context)

    except:
        context = {
            "post": post,
            "comments": post.comments.all(),
            "user": None,
            "comments_count": post.comments.all().count(),
            "viewing_user": request.user.username,
            'communities': communities,
            "action": "Post",
            "actionURL": "https://i.imgur.com/k3VFgYR.png",
            "ads" : getRandomAds()
        }
    if request.method == "POST":
        if request.user.is_authenticated:
            comment = Comment(
                article=post, text=request.POST['text'], posted_by=request.user)
            comment.save()
            return redirect('/'+str(post_id)+"#cm")
        else:
            messages.info(request, 'You must be logged in to post a comment')
            return render(request, "project_G3/detail.html", context)
    context = {
        "post": post,
        "comments": post.comments.all(),
        "comments_count": post.comments.all().count(),
        "viewing_user": request.user.username,
        'communities': communities,
        "action": "Post",
        "actionURL": "https://i.imgur.com/k3VFgYR.png",
        "ads" : getRandomAds()
    }
    return render(request, "project_G3/detail.html", context)


@login_required(login_url='/auth/login/')
def delete(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404("Post has already been deleted or doesn't exist")
    if request.user == post.author:
        post.author.userprofile.countLikes -= post.num_likes
        post.author.userprofile.countDislikes -= post.num_dislikes
        post.author.userprofile.save()
        post.delete()
    return redirect(index)


@login_required(login_url='/auth/login/')
def delete_comment(request, comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
        post_id2 = comment.article_id
        # print(post_id2)
    except Comment.DoesNotExist:
        raise Http404("Comment has already been deleted or doesn't exist")
    comment.delete()
    return redirect('/'+str(post_id2)+"#cm")


def reply_comment(request, comment_id):
    try:
        comment = Comment.objects.get(pk=comment_id)
        post_id = comment.article_id
    except Comment.DoesNotExist:
        raise Http404("Comment does not exist")
    if request.method == "POST":
        if request.user.is_authenticated:
            reply = Reply(
                comment=comment, text=request.POST['reply_comment'], posted_by=request.user)
            reply.save()
            return redirect('/'+str(post_id)+'#cm')
        else:

project_G3/templates/base(settings).html
{% load static %}
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body style="background-color:white;">
    <nav id="navbar" class="navbar navbar-expand-lg navbar-light sticky-top " style="background-color: #FFFFFF;">

        <a class="navbar-brand" href="/">
            <img src="{% static 'img/frT3.png' %}" alt="" class="navbar-brand" width="140" height="60">
        </a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <!-- <li class="nav-item"><a class="nav-link" href="/">Home</a></li> -->
                <!-- <li class="nav-item"><a class="nav-link" href="/users">Users</a></li> -->
                <!-- <li class="nav-item"><a class="nav-link" href="/mainpage">Mainpage</a></li> -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <img class="rounded-circle img-responsive" width = "20px" height = "20px" 
                        src = "{{ actionURL }}" onerror="this.onerror=null; this.src='https://i.imgur.com/zmZkm8I.png'"><img>
                        {% if action %}
                        {{ action | truncatechars:20}}
                        {% else %}
                        Home
                        {% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <!-- reddit feeds -->
                        <a class = "pl-2 text-secondary" style="font-size: small;">FREDDIT FEEDS</a>
                        <div class = "dropdown-divider"></div>
                        <a class = "dropdown-item" href = "/">
                            <img class = "rounded-circle img-responsive" width = "20px" height = "20px" src = "https://i.imgur.com/zmZkm8I.png">
                            Home
                        </a>
                        <a class = "dropdown-item" href = "/mainpage">
                            <img class = "rounded-circle img-responsive" width = "20px" height = "20px" src = "https://i.imgur.com/uOQZrhr.png">
                            Mainpage
                        </a>
                        <!-- My communities -->
                        <a class = "pl-2 text-secondary" style="font-size: small;">MY COMMUNITIES</a>
                        <div class = "dropdown-divider"></div>
                        {% for comm in communities %}
                            <a class="dropdown-item" href="{% url 'comm:communityDisplay' comm.name %} ">
                                <img class="rounded-circle img-responsive" width = "20px" height = "20px" src = "{{ comm.avatar.url }}" onerror="this.onerror=null; this.src='https://i.imgur.com/DM4Bt8m.png'"><img>
                                fr/{{ comm.name | truncatechars:20}}
                            </a>
                        {% endfor %}
                        <!-- other contents -->
                        <a class="pl-2 text-secondary" style="font-size: small;" >OTHER</a>
                        <div class = "dropdown-divider"></div>
                        <a class="dropdown-item" href="/communityCreate">
                            <img class = "rounded-circle img-responsive" width = "20px" height = "20px" src = "https://i.imgur.com/jZ34VhH.jpg">
                            Create a community
                        </a>
                        <a class="dropdown-item" href="/postCreate">
                            <img class = "rounded-circle img-responsive" width = "20px" height = "20px" src = "https://i.imgur.com/k3VFgYR.png">
                            Create a post
                        </a>
                        <a class="dropdown-item" href="/editprofile">
                            <img class = "rounded-circle img-responsive" width = "20px" height = "20px" src = "https://i.imgur.com/nWmEA9L.png">
                            Edit profile
                        </a>
                    </div>
                </li>

            </ul>


            {% if community %}
            <form class="form-inline my-2 my-lg-0 ml-auto" action="{% url 'comm:searchComm' community.name %}">
                <input name="q" class="form-control mr-sm-2"  type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {% else %}
            <form class="form-inline my-2 my-lg-0 ml-auto mr-3" action="{% url 'search:searchContent' %} ">
                <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            {%endif%}
            <!-- mainpage -->
            <a class = "shortcut ml-2 mr-2" href = "/mainpage" style="border-right: 1px solid black;">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-map-fill" viewbox="0 0 16 16">
                    <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.598-.49L10.5.99 5.598.01a.5.5 0 0 0-.196 0l-5 1A.5.5 0 0 0 0 1.5v14a.5.5 0 0 0 .598.49l4.902-.98 4.902.98a.502.502 0 0 0 .196 0l5-1A.5.5 0 0 0 16 14.5V.5zM5 14.09V1.11l.5-.1.5.1v12.98l-.402-.08a.498.498 0 0 0-.196 0L5 14.09zm5 .8V1.91l.402.08a.5.5 0 0 0 .196 0L11 1.91v12.98l-.5.1-.5-.1z"/>
                </svg>
                <span class = "shortcutText">All</span>
            </a>
            <!-- Create post icon -->
            <a class="shortcut ml-2" href = "/postCreate">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewbox = "0 0 16 16"> 
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg>
                <span class = "shortcutText">Create post</span>
            </a>

            <!-- create community icon -->
            <a class = "shortcut ml-2" href = "/communityCreate">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-people-fill" viewbox = "0 0 16 16">
                    <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd" d="M5.216 14A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216z"/>
                    <path d="M4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
                </svg>
                <span class = "shortcutText">Create community</span>
            </a>
            <!-- edit your profile -->
            {% if not request.user.is_anonymous %}
            <a class = "shortcut ml-2" href = "{% url 'userpage:userpage' request.user %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewbox="0 0 16 16">
                    <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                    <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                </svg>
                <span class = "shortcutText">Your Page</span>
            </a>
            {% endif %}
            <!-- <p>{{ user }}</p> -->
            {% if not request.user.is_anonymous %}
            <!-- <span class="ml-5">Hi &VeryThinSpace;</span> -->
            <div class="btn-group" id = "userShortcut">
                <button type="button" style="background-color: #FFFFFF;" class="btn dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <span>
                        <img src="{{user.userprofile.avatar.url}}"
                        onerror="this.onerror=null; this.src='https://i.ibb.co/pPh0Pyh/download.png'" alt="Avatar"
                        class="rounded-circle img-responsive" height="30px" width="30px">                
                        {{ user }}
                    </span>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" href="/editprofile">
                        <span>
                            <i class="fas fa-user-edit"></i>
                        </span>
                        Edit profile
                    </a>
                    <a class="dropdown-item" href="{% url 'authentic:logoutUser' %} "> 
                        <span class="mr-1">
                            <i class="fas fa-sign-out-alt"> </i>
                        </span>
                         Logout
                        
                    </a>
                </div>
            </div>

            {% else %}
            <a href="/auth/login" class="btn btn-outline-info ml-4">Sign up/Sign in</a>
            {%endif%}


        </div>
    </nav>
    {% block content %}

    {% endblock %}
</body>

</html>

project_G3/templates/userSimple.html
<div class="mb-2" style="position: relative;">
    <img class="float-left rounded-circle img-responsive" width="50px" height="50px"
        src="{{ user.userprofile.avatar.url }}"
        onerror="this.onerror=null; this.src='https://i.ibb.co/pPh0Pyh/download.png'"><img>
    <a class="float-left ml-2" href="{% url 'userpage:userpage' user %}">{{ user.username | truncatechars:15 }}</a>
    
    <div class="" style="font-size: 12px;  font-weight: lighter; position: absolute; left: 60px; top: 20px;">
        {{user.userprofile.createdposts.count}} Posts
    </div>
   
    <span class="ani float-right">
        {% include 'follow.html' %}  
      </span>
    {% if user.userprofile.about %}
    <p class="float-right col-6 mr-3" style="color: rgba(0, 0, 0, 0.514);font-size: small;">
        {{user.userprofile.about | truncatechars:50}}
    </p>
    {% endif %}


</div>

project_G3/templates/welcomePost.html
<div class="post rounded " style="padding-bottom: 5px;" >
    <div class="pl-3 pt-2">
        
        <!-- <p class="mt-4"></p> -->
        <div class="text-center " style="color: rgb(255, 81, 0);font-size:30px;font-family:Monaco,monospace">
            <span>Welcome to FReddit!</span>
        </div>
            


    </div>

    <div class="img-container mt-3 mb-3">
        <img src="https://i.pinimg.com/originals/8c/9a/07/8c9a079986a4ce112882fea6db3ffdee.gif"
            alt="Welcome to FReddit!" style="align-self: auto; width: fit-content; font-size: large;">
    </div>


    <div class="mt-4 pl-3 alert alert-info" role="alert">

        
        Homepage will only display the posts from your joined communities, your followed users, or your own
        posts.
        <br>Please go to the
        <a href="/mainpage" class="alert-link">Mainpage</a> to see all the posts.
        <br>
        <div class="mt-2 text-center" style="font-size: large;color: green;">
            Have nice moments using FReddit 😁
        </div> 
        

    </div>


    


    

</div>