authentic/urls.py
from django.urls import path
from . import views

app_name = 'authentic'

urlpatterns = [
    path('login/' , views.registerUser.as_view(), name='registerUser'),
    path('logout/', views.logoutUser, name='logoutUser')

]

comm/urls.py
from django.urls import path
from . import views 

app_name = 'comm'

urlpatterns = [
	path('<str:community_name>', views.communityDisplay, name = "communityDisplay"),
	path('<str:community_name>/search/', views.searchComm, name = "searchComm"),
	path('<str:community_name>/join/', views.API_join, name = "API_join"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from project_G3 import views as project_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project_G3.urls')),
    path('auth/', include('authentic.urls')),
    path('r/', include('comm.urls')),
    path("search/", include('search.urls')),
    path('u/', include('userpage.urls'))
]

authentic/models.py
from django.db import models

# Create your models here.

authentic/forms.py
from django import forms

class registerForm(forms.Form):
    username= forms.CharField(max_length = 20)
    email = forms.EmailField()
    password = forms.CharField(max_length = 20, widget= forms.PasswordInput)

class loginForm(forms.Form):
    username= forms.CharField(max_length = 20)
    password = forms.CharField(max_length = 20, widget= forms.PasswordInput)

authentic/views.py
from django.shortcuts import render, redirect
from .forms import registerForm, loginForm
from django.views import View
from django.contrib.auth.models import User
from django.http import HttpResponse, Http404
from django.db import IntegrityError
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from project_G3.models import UserProfile, Community
from django.utils import timezone

# Create your views here.
class registerUser(View):
    def get(self, request):
        rF = registerForm
        if 'next' in request.GET:
            next = request.GET['next']
        else:
            next = None
        return render(request, 'authentic/login.html', {'rF': rF, 'next': next})

    def post(self, request):
        if request.POST['action'] == 'SU':
            # print(request.POST['username'])
            username = request.POST['usernameSU']
            email = request.POST['emailSU']
            password = request.POST['passwordSU']
            try:
                user = User.objects.create_user(username, email, password)
            except IntegrityError as e:
                messages.info(
                    request, 'Existed username!\n You want to login? ')
                return render(request, 'authentic/login.html')
            user.save()
            player, created = UserProfile.objects.get_or_create(user=user) 
            login(request, user)
            # if 'next' in request.POST:
            #     print('--')
            #     print(request.POST['next'])
            try:
                return redirect(request.POST['nextpage'])
            except:
                # print("No thing")
                return redirect('/')
            return redirect('/')
        # print(request.POST['username'])
        else:
            username = request.POST['usernameSI']
            password = request.POST['passwordSI']
            user = authenticate(request, username=username, password=password)
            if request.user.is_authenticated:
                userProfile = UserProfile.objects.get(user = request.user)
                # print(userProfile)
                userProfile.lastLogout = timezone.now()
                userProfile.save()
                logout(request)
            if user is not None:
                login(request, user)
                try:
                    return redirect(request.POST['nextpage'])
                except:
                    # print("No thing")
                    return redirect('/')
                return redirect('/')
            else:
                messages.info(request, 'Incorrect username or password! ')
                return render(request, 'authentic/login.html')


def logoutUser(request):
    # print(-1)
    userProfile = UserProfile.objects.get(user = request.user)
    # print(userProfile)
    userProfile.lastLogout = timezone.now()
    userProfile.save()
    logout(request)
    return redirect('/')

authentic/templates/authentic/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <!-- https://github.com/sefyudem/Sliding-Sign-In-Sign-Up-Form -->
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" /> -->

  <link rel="stylesheet" href="{% static 'css/login.css' %} ">
  <title>Sign in & Sign up</title>
</head>

<body>
  <!-- <a href="https://github.com/sefyudem/Sliding-Sign-In-Sign-Up-Form"> Source code </a> -->
  <div class="container">
    <div class="forms-container">
      <div class="signin-signup">
        <form action="" method="POST" class="sign-in-form">
          {% csrf_token %}

          <input type="hidden" name="action" value="SI">
          <input type="hidden" name="nextpage" value={{ next }}>
          <h2 class="title">Sign in</h2>
          <div class="input-field">
            <i class="fas fa-user"></i>
            <!-- <input type="text" placeholder="Username" /> -->
            <input autocomplete="off" type="text" name="usernameSI" maxlength="20" required="" id="id_username"
              placeholder="Username">
          </div>
          <div class="input-field">
            <i class="fas fa-lock"></i>
            <!-- <input type="password" placeholder="Password" /> -->
            <input autocomplete="off" type="password" name="passwordSI" maxlength="20" required="" id="id_password"
              placeholder="Password">
          </div>
          <input type="submit" value="Login" class="btn solid" />
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
          </ul>
          {% endif %}
          {% if 'next' in request.GET %}
          <ul class="messages">
            
            <li >You have to log in to perform this task!! :< </li>
            
          </ul>

          {% endif %}

        </form>
        <form action="" method="POST" class="sign-up-form">
          {% csrf_token %}
          <input type="hidden" name="action" value="SU">
          <input type="hidden" name="nextpage" value={{ next }}>
          <h2 class="title">Sign up</h2>
          <div class="input-field">
            <i class="fas fa-user"></i>
            <!-- <input type="text" placeholder="Username" /> -->
            <input autocomplete="off" type="text" name="usernameSU" maxlength="20" required="" id="id_username"
              placeholder="Username">
          </div>
          <div class="input-field">
            <i class="fas fa-envelope"></i>
            <!-- <input type="email" placeholder="Email" /> -->
            <input autocomplete="off" type="email" name="emailSU" required="" id="id_email" placeholder="Email">
          </div>
          <div class="input-field">
            <i class="fas fa-lock"></i>
            <!-- <input type="password" placeholder="Password" /> -->
            <input autocomplete="off" type="password" name="passwordSU" maxlength="20" required="" id="id_password"
              placeholder="Password">
          </div>
          <input type="submit" class="btn" value="Sign up" />

        </form>
      </div>
    </div>

    <div class="panels-container">
      <div class="panel left-panel">
        <div class="content">
          <h3>New here ?</h3>
          <p>
            Let's sign up
          </p>
          <button class="btn transparent" id="sign-up-btn">
            Sign up
          </button>
        </div>
        <img src="{% static 'img/6.svg' %}" class="image" alt="" />
      </div>
      <div class="panel right-panel">
        <div class="content">
          <h3>One of us ?</h3>
          <p>
            Let's sign in
          </p>
          <button class="btn transparent" id="sign-in-btn">
            Sign in
          </button>
        </div>
        <img src="{% static 'img/4.svg' %}" class="image" alt="" />
      </div>
    </div>
  </div>

  <script src="{% static 'js/login.js' %}"></script>


</body>

</html>

authentic/templates/authentic/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New user</title>
</head>
<body>
    <form action="" method=POST>
        {% csrf_token %}
        {{ rF.as_p }}
        <input type="submit" >

    </form>
    
</body>
</html>